dataset_path: /datasets/deepfake

dataset_limit: null

batch_size: 64
epochs: 20
num_workers: 8

model: resnet50

checkpoint_interval: 500
failure_rate_per_sec: 0.02
fixed_interval: 30
checkpoint_cost_estimate: 3.0

strategy: epoch
